### ISSUE TITLE
Creating a Token

### ISSUE THREAD

**Issue by brookton** [Tkd-Alex/Telegram-InstaPy-Scheduling#1]
Hi. Could you help me figure out how to create a token with @botfather ? I'm interested in trying this but I'm not sure how to go about that step. Not seeing instructions or a working link for that...

**Comment by Tkd-Alex** [comment]
Sure.
1. Contact @BotFather on Telegram.
2. /start
3. /newbot
4. Insert a name for bot
4. Insert a username for bot.
5. Copy the token gived by BotFather.

It's very easy
