### ISSUE TITLE
ImportError: cannot import name 'TelegramError'

### ISSUE THREAD

**Issue by MarshallJohansson** [Tkd-Alex/Telegram-InstaPy-Scheduling#13]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from telegram.ext import Updater, CommandHandler, Job, CallbackQueryHandler
  File "/home/aydar/.local/lib/python3.5/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "/home/aydar/.local/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError'

How to fix?

**Comment by Tkd-Alex** [comment]
Have you installed all requirement in [requirements.txt ](https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/blob/master/requirements.txt)?
```
pip install -r requirements.txt
```

**Comment by MarshallJohansson** [comment]
of course!

**Comment by Tkd-Alex** [comment]
See this issue: https://github.com/python-telegram-bot/python-telegram-bot/issues/395

**Comment by MarshallJohansson** [comment]
I also tried it - did not help

**Comment by MarshallJohansson** [comment]
thanks for the solution

**Comment by Koddom** [comment]
Как ни странно, но именно удалив папку telegram, а затем сново установив её через командную строку pip, проблема исчезла. При этом ничего перезапускать не пришлось. Яблоко и PyCharm
