### ISSUE TITLE
ImportError when i execute main.py

### ISSUE THREAD

**Issue by xnardo** [Tkd-Alex/Telegram-InstaPy-Scheduling#14]
Hello, when execute **"python main.py"** i receive me the next mistake:

`Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts import scripts
  File "/path/InstaPy/Telegram-InstaPy-Scheduling/scripts.py", line 4, in <module>
    import random, time, traceback, instapy
ImportError: No module named instapy`

And then i tried with **"python3 main.py"** and i receive the next:

`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from telegram.ext import Updater, CommandHandler, Job, CallbackQueryHandler
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError'`

I hope do you can help me. Thanks a lot!

**Comment by Tkd-Alex** [comment]
Have you copied the instapy folder to main folder of Telegram-InstaPy-Scheduling?
You can also clone this directory inside InstaPy folder 😄 

From #12 

> Copy the instapy folder in the same folder of Telegram-InstaPy-Scheduling.
https://github.com/timgrossmann/InstaPy/tree/master/instapy

**Comment by xnardo** [comment]
Yes was that :D 

**Thanks a lot!**

Now i can not start the command in telegram, but i imagine than i need to open i new issue or try more.
