### ISSUE TITLE
Show Results on End

### ISSUE THREAD

**Issue by pttnx** [Tkd-Alex/Telegram-InstaPy-Scheduling#16]
Is there a way to let the bot echo results of the ended script run? Someting like the original message fired by InstaPy, after session.end() ?

**Comment by Tkd-Alex** [comment]
uhmm when the bot complete the session the output shoul be send in telegram chat

**Comment by Tkd-Alex** [comment]
uhmm i see multiple error in your message/log.

1. 
```python
TypeError: set_mandatory_words() takes from 1 to 2 positional arguments but 3 were given
```
The method takes from 1 to 2 arguments but 3 given.

2. 
```python
ValueError: signal only works in main thread
```
I have found a problem with Thread and Instapy. Some method use signal and signal doesn't work in thread. I've solved atm with comment the use of **with interruption_handler():**

3. 
```python
FileNotFoundError: [Errno 2] No such file or directory: 'logs/general.log'
```
Your logs file should be placed in:
**/home/xxx/projects/InstaPy/telegram/logs/general.log**

**Comment by pttnx** [comment]
i fixed number 1 and 3, so i just need to comment out interruption_handler(): from util.py ?

**Comment by Tkd-Alex** [comment]
yup :)

**Comment by pttnx** [comment]
the whole block?

**Comment by pttnx** [comment]
by commenting the interruption_handler i got a whole bunch of other errors, which even stayed, when i reverted my changes. For now i simply use the basic script again. Looking forward for your commit :)

**Comment by mgconejero** [comment]
i am getting this issue: 
FileNotFoundError: [Errno 2] No such file or directory: 'settings.json'

and i have the settings.json file in the same folder.. weird.

Love the idea of this telegram bot though

**Comment by pttnx** [comment]
did you cd into the telegram-instapy-folder ?

**Comment by mgconejero** [comment]
Great, i will give it a try in a moment!!

**Comment by HCWcoder** [comment]
```
C:\Users\JayPixx\Documents\GitHub\InstaPy>python main.py

DevTools listening on ws://127.0.0.1:51595/devtools/browser/6ce05304-ffc0-468e-9c78-10416f3a7eff

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-13 22:50:20] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


...................................................................
INFO [2018-12-13 22:50:33] [xxx]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Traceback (most recent call last):
  File "C:\Users\JayPixx\Documents\GitHub\InstaPy\scripts.py", line 19, in biglikers
    session.end()
  File "C:\Users\JayPixx\Documents\GitHub\InstaPy\instapy\instapy.py", line 3880, in end
    self.live_report()
  File "C:\Users\JayPixx\Documents\GitHub\InstaPy\instapy\instapy.py", line 4356, in live_report
    bot_sendtext(self.liked_img)
NameError: name 'bot_sendtext' is not defined
```

**Comment by HCWcoder** [comment]
```
Traceback (most recent call last):
  File "C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\JayPixx\Documents\GitHub\InstaPy\process.py", line 70, in run
    with open('{}/logs/{}/general.log'.format(self.instapy_path, self.username), "r") as f:
OSError: [Errno 22] Invalid argument: '/C:/Users/JayPixx/Documents/GitHub/InstaPy/logs/socialmedialb/general.log'
```
