### ISSUE TITLE
[Windows] Take a Screenshot and send it to telegram!

### ISSUE THREAD

**Issue by HCWcoder** [Tkd-Alex/Telegram-InstaPy-Scheduling#22]
This is a option i  needed to check my CMD logs of Main.py while runing : 

Add this Function to Main.py

```
import requests
def scrn(bot, update):

    update.message.reply_text('Taking the screenshoot')
    
    img=ImageGrab.grab()
    img.save('screenshot.png')

    url = "https://api.telegram.org/bot"+telegram_token+"/sendPhoto";
    files = {'photo': open('screenshot.png', 'rb')}
    data = {'chat_id' : allowed_id[0]}
    
    r= requests.post(url, files=files, data=data)
```

then add this handler code to the bottom next to the others : 

`
    dp.add_handler(CommandHandler("scrn", scrn))
`

In your telegram send /scrn to get it,

P.S: `pip install requests` or `pip3 install requests` If missing

**Comment by HCWcoder** [comment]
@Tkd-Alex 
Im sure you can make it work with your code with a better lines of code 🍡  :D 

Thanks alot

**Comment by Tkd-Alex** [comment]
I don't understand why this command is helpful.
You want the screen of main,py logs right?

I suggest to create a command like this:
__/logs 10__

Where the args (ex: 10) are the lines of logs to send in answer after the command.
What do you think about? It's very easy to develop

**Comment by Tkd-Alex** [comment]
It should be work.
I can't help you atm, As soon as I have free time I'll implement this feature for you :)

**Comment by HCWcoder** [comment]
> It should be work.
> I can't help you atm, As soon as I have free time I'll implement this feature for you :)

I think theres an issue in here only 
`update.message.reply_text(line, parse_mode='HTML')`

if you can just help me in this maybe  `line` need to be passed to telegram in a different way
