### ISSUE TITLE
console freezes when launching main.py?

### ISSUE THREAD

**Issue by TarekJ03** [Tkd-Alex/Telegram-InstaPy-Scheduling#28]
I followed all steps in the tutorial, but when I try to run main.py I don't get any response or anything. It seems that it is simply loading, but even after 10 mins it didn't stop. .Can someone help me?

**Comment by Tkd-Alex** [comment]
Hi! Have you solved?

**Comment by TarekJ03** [comment]
The way I understand it now, the bot is only active when the script is running. When I opened the issue i thought that it was something similar to setup.py and not the bot itself. Since I don't use my raspberry for anything else than InstaPy, it's not a problem that the command line doesn't accept any inputs while main.py is running, I simply thought it wouldn't do anything because there was no response and I expected something like "no errors, the bot is now running" or something like that. Btw, the order of args in readme for /set is different from the actual one.
