### ISSUE TITLE
main.py onStart?

### ISSUE THREAD

**Issue by TarekJ03** [Tkd-Alex/Telegram-InstaPy-Scheduling#29]
Is there any way of starting main.py everytime the computer starts? Cron and rc.local don't work from what I tested. My machine is a raspberry pi 3b+ that runs raspbian in cli mode.

**Comment by Tkd-Alex** [comment]
uhm you should create a service and enable with systemctl.
follow this tutorial: https://timleland.com/how-to-run-a-linux-program-on-startup/

ExecStart= **python3 main.py &** should be work

**Comment by TarekJ03** [comment]
Thanks for your quick answer, but it doesn't work. systemctl status <job_name> outputs:

> Dez 31 18:35:46 raspberrypi systemd[1]: [/etc/systemd/system/telegram.service:1] Assignment outside of section. Ignoring.
> Dez 31 18:35:46 raspberrypi systemd[1]: [/etc/systemd/system/telegram.service:3] Assignment outside of section. Ignoring.
> Dez 31 18:35:46 raspberrypi systemd[1]: [/etc/systemd/system/telegram.service:4] Assignment outside of section. Ignoring.
> Dez 31 18:35:46 raspberrypi systemd[1]: [/etc/systemd/system/telegram.service:8] Executable path is not absolute, ignoring: cd /home/pi/Projects/Telegram-InstaPy-Scheduling
> Dez 31 18:35:46 raspberrypi systemd[1]: telegram.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.

Do you know what to do?

**Comment by Tkd-Alex** [comment]
No bro, I don't know

**Comment by Tkd-Alex** [comment]
Hi! You can try to do:
`cd /path/to ; python3 main.py`
