### ISSUE TITLE
  File "main.py", line 30, in <module>     except (FileNotFoundError, IOError):

### ISSUE THREAD

**Issue by phorest0** [Tkd-Alex/Telegram-InstaPy-Scheduling#35]
I've got this error after trying to run main.py 

`$ python main.py
Traceback (most recent call last):

  File "main.py", line 30, in <module>

    except (FileNotFoundError, IOError):

NameError: name 'FileNotFoundError' is not defined
`

**Comment by TarekJ03** [comment]
Are you in the project's folder?

**Comment by phorest0** [comment]
> Are you in the project's folder?

Yes, Screen:
<img width="517" alt="screen shot 2019-01-31 at 14 34 36" src="https://user-images.githubusercontent.com/20317093/52054527-854f4480-2565-11e9-9c9e-4bc427c99d70.png">

**Comment by TarekJ03** [comment]
And you're sure the file is in the folder?

**Comment by phorest0** [comment]
> And you're sure the file is in the folder?
Here is the list of all files in this folder
<img width="906" alt="screen shot 2019-01-31 at 14 49 56" src="https://user-images.githubusercontent.com/20317093/52055388-f42d9d00-2567-11e9-9795-8a3c9bfc010d.png">

**Comment by TarekJ03** [comment]
Do you use python3? Because it seems like python can't find an error named "FileNotFoundError"

**Comment by phorest0** [comment]
Ops, sorry. My bad, I'v got an 2.7 version.
