### ISSUE TITLE
Unable to view logs

### ISSUE THREAD

**Issue by captv89** [Tkd-Alex/Telegram-InstaPy-Scheduling#37]
Hello,
Firstly thank you for this amazing bot. It makes running InstaPy so easy. I have been trying to read the logs using this format: `/logs username 10`
I have checked the path for log files and found the logs are being written when the script runs.
But I am not getting any reply from the bot. No error is being shown in the instance too.
pls help.. thank you.

**Comment by Tkd-Alex** [comment]
Thank for the report. 
I'll fix asap :)

**Comment by Tkd-Alex** [comment]
Fixed https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/pull/41
