### ISSUE TITLE
[Question] How to set InstaPy's workspace.

### ISSUE THREAD

**Issue by brunano21** [Tkd-Alex/Telegram-InstaPy-Scheduling#38]
With InstaPy, there is the possibility to set its [workspace](https://github.com/timgrossmann/InstaPy#workspace-folders), where db and logs are stored.
How can I achieve the same if I'm using the telegram bot?
Thanks!

**Comment by TarekJ03** [comment]
It's explained right there :grin: look under **Custom Workspace**

**Comment by brunano21** [comment]
So, are you saying I can put the following into _scripts.py_ too?
```
from instapy import set_workspace
set_workspace("C:\\My\\Custom\\Path\\InstaPy\\")
```
