### ISSUE TITLE
Username not saved

### ISSUE THREAD

**Issue by Kevdome3000** [Tkd-Alex/Telegram-InstaPy-Scheduling#39]
I keep getting a response from bot saying "Sorry, username not saved"

I am supposed to save username in an array = users right?

**Comment by TarekJ03** [comment]
Hi @Kevdome3000, what is the full error output?

**Comment by Kevdome3000** [comment]
Hi there, 

I'm not getting an error on the backend. Maybe I misunderstood how the bot works. Do I need to /add_user each time I run the bot or can I store a user to always be the default?

**Comment by Kevdome3000** [comment]
Figured it out :)
