### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by diogoribeirodev** [Tkd-Alex/Telegram-InstaPy-Scheduling#55]
dead?

**Comment by Tkd-Alex** [comment]
Luckily for me, I'm alive 😂

The project it's technically dead, but I someone what's to resuscitate, we could working on it 😁

**Comment by diogoribeirodev** [comment]
I want to resurrect it, but I'm still a beginner in python, and intermediate in C#, so I don't know if I would be a big help. Btw love the twitch points miner bot, been using it non stop and it works perfectly

**Comment by diogoribeirodev** [comment]
But i can help if needed (as far as i understand the code and do it), it will help me improve my python skills.
