### ISSUE TITLE
Add multiple threads

### ISSUE THREAD

**Issue by lologibus2** [Tkd-Alex/Telegram-InstaPy-Scheduling#6]
Hello, first thank for the great feature. 

I'd like to set up different threads for differents tasks, for example  : 
 - One for following user's followers to be set twice a day
 - One for liking by location
 - One for unfollowing every day at special time

It would be great if i could schedule the tasks independentely from telegram:
something like : 
  /set task1
  /set task2

Do you think it can be easily implemented ? 
Thanks a lo

**Comment by Tkd-Alex** [comment]
Hi, ty for using Telegram-InstaPy-Scheduling. I appreciate your suggestion.
If you read my last answer to #5 i've suggest to change the **\/set** command like a GUI to help the user to create a custom InstaPy script. Obviously if we use this approach it will become easy use different script for different thread and different schedule.
Maybe it could be something like that

| Command  | Parameters                           | Description                     |
|----------|--------------------------------------|---------------------------------|
| \/set     | \<name\> \<hh:mm:ss\>                    | Set new schedule \<script, time\> |
| \/new     | \<name\> ... ask input (example in #5)  | Create new script               |
| \/enable  | \<name\>                               | Enable schedule                 |
| \/disable | \<name\>                               | Disable schedule                |
